services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./sql/:/docker-entrypoint-initdb.d/

volumes:
  pgdata:
    name: pgdata

networks: 
  postgres-network:
    driver: bridge